### ISSUE TITLE
Browse does not find all Items on my OPC

### ISSUE THREAD

**Issue by jogibear9988** [convertersystems/opc-ua-client#28] opened 2017-04-04 09:41 UTC
If I use your Visual Studio Addin, or my COde, I can not find all Datablocks on my PLC. If I use the Client from https://www.unified-automation.com/downloads/opc-ua-clients/file/download/details/uaexpert-v140.html it works. (and is much faster in loading the information)

**Comment by awcullen** [comment] 2017-04-04 12:40
Please tell me more about the missing blocks. Is it always the same blocks? Would it be possible to send a screenshot?

About performance, UaExpert browses the nodes first. Then, if you select the node, UaExpert reads the attributes. UaBrowser both browses and reads the attributes (datatype, arrayrank, etc) at once. I prefer to see the datatype when I'm browsing. But I have not used a 1500. Is the UaBrowser performance too slow on a 1500?

**Comment by awcullen** [comment] 2017-04-04 14:42
I uploaded a new version 1.5.9 of UaBrowser to the Marketplace. (Maybe Visual Studio will notify you?)
This contains the bugfix for the DataLengthException that you reported (and took me a while to fix).
Maybe this is related.

**Comment by jogibear9988** [comment] 2017-04-04 15:16
The new Version works....

**Comment by awcullen** [comment] 2017-04-04 15:20
Fantastic!

**Comment by jogibear9988** [comment] 2017-04-04 15:30
When I use a newer Version of your Assembly as 1.5.7 I got this Exception:

System.IO.FileLoadException: Die Datei oder Assembly "Microsoft.Extensions.Logging.Abstractions, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
Dateiname: "Microsoft.Extensions.Logging.Abstractions, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" ---> System.IO.FileLoadException: Die Datei oder Assembly "Microsoft.Extensions.Logging.Abstractions, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
Dateiname: "Microsoft.Extensions.Logging.Abstractions, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"

**Comment by awcullen** [comment] 2017-04-04 15:36
Yes, 1.5.9 requests "Microsoft.Extensions.Logging.Abstractions, Version=1.1.1.0"
Will that be a problem?

**Comment by jogibear9988** [comment] 2017-04-04 15:50
i've solved it with a app.config entry!

**Comment by jogibear9988** [comment] 2017-04-04 15:50
one more problem, i've a timeout for my request! can i increase it?

**Comment by awcullen** [comment] 2017-04-04 16:03
If you are talking about UaBrowser, then unfortunately I don't expose the timeouts now. The default is 15 seconds for each request. Too small? Would 30 seconds be enough?

If you are using the UaTcpSessionChannel in code, then modify the constructor
```
                                this.session = new UaTcpSessionChannel(
                                this.localDescription,
                                this.CertificateStore,
                                this.userIdentity,
                                selectedEndpoint, 
                                timeoutHint: 30000);
```

**Comment by jogibear9988** [comment] 2017-04-05 07:38
Is it normal that a subscribe to 1000 Tags takes about 30 seconds?

**Comment by awcullen** [comment] 2017-04-05 13:32
I installed UaCPPServer from http://www.unified-automation.com/ on a separate PC.
I modified the ConsoleApp from my opc-ua-samples repo, to create a subscription 
with 1000 monitored items. 
The stopwatch runs 22 - 24 milliseconds.

Security set to Basic256 - Sign and Encrypt

```
var watch = new Stopwatch();
var itemsToCreate = new MonitoredItemCreateRequest[1000];
for (int i = 0; i < 1000; i++)
{
    itemsToCreate[i] =
        new MonitoredItemCreateRequest { ItemToMonitor = new ReadValueId { NodeId = NodeId.Parse($"ns=2;s=Demo.Massfolder_Dynamic.Variable{string.Format("0000", i)}"), AttributeId = AttributeIds.Value }, MonitoringMode = MonitoringMode.Reporting, RequestedParameters = new MonitoringParameters { ClientHandle = (uint)i, SamplingInterval = -1, QueueSize = 0, DiscardOldest = true } };
}

Console.WriteLine("Step 6 - Create a subscription.");
watch.Restart();

var subscriptionRequest = new CreateSubscriptionRequest
{
    RequestedPublishingInterval = 1000,
    RequestedMaxKeepAliveCount = 10,
    RequestedLifetimeCount = 30,
    PublishingEnabled = true
};
var subscriptionResponse = await session.CreateSubscriptionAsync(subscriptionRequest).ConfigureAwait(false);
var id = subscriptionResponse.SubscriptionId;

Console.WriteLine("Step 7 - Add items to the subscription.");
var itemsRequest = new CreateMonitoredItemsRequest
{
    SubscriptionId = id,
    ItemsToCreate = itemsToCreate,
};
var itemsResponse = await session.CreateMonitoredItemsAsync(itemsRequest).ConfigureAwait(false);
watch.Stop();
Console.WriteLine($"ElapsedMilliseconds: {watch.ElapsedMilliseconds}");
```

**Comment by jogibear9988** [comment] 2017-04-13 05:37
i've talked to siemens! their opc has limited performance

**Comment by rebj1011** [comment] 2018-08-07 09:31
Hey Andrew,
i've the same porblem as jogi. If i start browsing my Siemens OpcUA server, i only get a few DBs. 
I'm using Visual Studio 17 including the .Net Framework 4.6.1 and your Workstation.UaBrowser fom the Marketplace. 
Could you pls help me?

**Comment by awcullen** [comment] 2018-08-07 19:31
You can also turn on logging to write any exceptions to a file:

1. Start notepad.exe as Administrator (by right click Run as Administrator).

2. Select File...Open.  Change Filter to "All files (* .*). Change directory to  "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE".  Select "devenv.exe.config".  (If that location is not correct, you can search for 'devenv.exe' in the Taskbar, then right click and choose Open file location..."). 

3. Edit the xml to end with:
```
    <system.diagnostics>
      <trace autoflush="false" indentsize="4">
        <listeners>
          <add name="myListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="C:\Users\Public\Documents\devenv.log" />
          <remove name="Default" />
        </listeners>
      </trace>
    </system.diagnostics>

  </configuration>
```
4. Save the file. Restart Visual Studio.

5. Use UABrowser and cause the problem. 

6. Use Explorer to see that the "devenv.log" file is created in "C:\Users\Public\Documents" directory.

**Comment by rebj1011** [comment] 2018-08-08 06:46
Ua Expert Resulat the list of the DBs is even longer that this snippet:
![grafik](https://user-images.githubusercontent.com/18597195/43820092-7eeed16a-9ae5-11e8-915e-8a3a25b9f3f0.png)

Result of the "Workstation ConsolApp" Code
``Step 1 - Describe this app.
Step 2 - Create a certificate store.
Step 3 - Create a session with your server.
Server is requesting UserName identity...
Enter user name:
Enter password: 
  Opened channel with endpoint '                                             '.
  SecurityPolicyUri: 'http://opcfoundation.org/UA/SecurityPolicy#Basic256'.
  SecurityMode: 'SignAndEncrypt'.
  UserIdentity: 'Workstation.ServiceModel.Ua.UserNameIdentity'.
Press any key to continue...
Step 4 - Browse the server namespace.
+ Root
  + C: 2:/Plc/C, Variable
  + Clock: 2:/Plc/Clock, Variable
  + I: 2:/Plc/I, Variable
  + IB: 2:/Plc/IB, Variable
  + ID: 2:/Plc/ID, Variable
  + IW: 2:/Plc/IW, Variable
  + M: 2:/Plc/M, Variable
  + MB: 2:/Plc/MB, Variable
  + MD: 2:/Plc/MD, Variable
  + MW: 2:/Plc/MW, Variable
  + Q: 2:/Plc/Q, Variable
  + QB: 2:/Plc/QB, Variable
  + QD: 2:/Plc/QD, Variable
  + QW: 2:/Plc/QW, Variable
  + T: 2:/Plc/T, Variable
  + connect_state: 2:/Plc/connect_state, Variable
  + DB1: 2:/Plc/DB1, Object
    + DB1.DBB: 2:/Plc/DB1.DBB, Variable
    + DB1.DBW: 2:/Plc/DB1.DBW, Variable
    + DB1.DBD: 2:/Plc/DB1.DBD, Variable
    + DB1.DBX: 2:/Plc/DB1.DBX, Variable
  + DB2: 2:/Plc/DB2, Object
    + DB2.DBB: 2:/Plc/DB2.DBB, Variable
    + DB2.DBW: 2:/Plc/DB2.DBW, Variable
    + DB2.DBD: 2:/Plc/DB2.DBD, Variable
    + DB2.DBX: 2:/Plc/DB2.DBX, Variable
  + DB3: 2:/Plc/DB3, Object
    + DB3.DBB: 2:/Plc/DB3.DBB, Variable
    + DB3.DBW: 2:/Plc/DB3.DBW, Variable
    + DB3.DBD: 2:/Plc/DB3.DBD, Variable
    + DB3.DBX: 2:/Plc/DB3.DBX, Variable
  + DB4: 2:/Plc/DB4, Object
    + DB4.DBB: 2:/Plc/DB4.DBB, Variable
    + DB4.DBW: 2:/Plc/DB4.DBW, Variable
    + DB4.DBD: 2:/Plc/DB4.DBD, Variable
    + DB4.DBX: 2:/Plc/DB4.DBX, Variable
  + DB5: 2:/Plc/DB5, Object
    + DB5.DBB: 2:/Plc/DB5.DBB, Variable
    + DB5.DBW: 2:/Plc/DB5.DBW, Variable
    + DB5.DBD: 2:/Plc/DB5.DBD, Variable
    + DB5.DBX: 2:/Plc/DB5.DBX, Variable
  + DB7: 2:/Plc/DB7, Object
    + DB7.DBB: 2:/Plc/DB7.DBB, Variable
    + DB7.DBW: 2:/Plc/DB7.DBW, Variable
    + DB7.DBD: 2:/Plc/DB7.DBD, Variable
    + DB7.DBX: 2:/Plc/DB7.DBX, Variable
  + DB8: 2:/Plc/DB8, Object
    + DB8.DBB: 2:/Plc/DB8.DBB, Variable
    + DB8.DBW: 2:/Plc/DB8.DBW, Variable
    + DB8.DBD: 2:/Plc/DB8.DBD, Variable
    + DB8.DBX: 2:/Plc/DB8.DBX, Variable
  + DB10: 2:/Plc/DB10, Object
    + DB10.DBB: 2:/Plc/DB10.DBB, Variable
    + DB10.DBW: 2:/Plc/DB10.DBW, Variable
    + DB10.DBD: 2:/Plc/DB10.DBD, Variable
    + DB10.DBX: 2:/Plc/DB10.DBX, Variable
  + DB11: 2:/Plc/DB11, Object
    + DB11.DBB: 2:/Plc/DB11.DBB, Variable
    + DB11.DBW: 2:/Plc/DB11.DBW, Variable
    + DB11.DBD: 2:/Plc/DB11.DBD, Variable
    + DB11.DBX: 2:/Plc/DB11.DBX, Variable
  + DB15: 2:/Plc/DB15, Object
    + DB15.DBB: 2:/Plc/DB15.DBB, Variable
    + DB15.DBW: 2:/Plc/DB15.DBW, Variable
    + DB15.DBD: 2:/Plc/DB15.DBD, Variable
    + DB15.DBX: 2:/Plc/DB15.DBX, Variable
  + DB16: 2:/Plc/DB16, Object
    + DB16.DBB: 2:/Plc/DB16.DBB, Variable
    + DB16.DBW: 2:/Plc/DB16.DBW, Variable
    + DB16.DBD: 2:/Plc/DB16.DBD, Variable
    + DB16.DBX: 2:/Plc/DB16.DBX, Variable
  + DB17: 2:/Plc/DB17, Object
    + DB17.DBB: 2:/Plc/DB17.DBB, Variable
    + DB17.DBW: 2:/Plc/DB17.DBW, Variable
    + DB17.DBD: 2:/Plc/DB17.DBD, Variable
    + DB17.DBX: 2:/Plc/DB17.DBX, Variable
  + DB18: 2:/Plc/DB18, Object
    + DB18.DBB: 2:/Plc/DB18.DBB, Variable
    + DB18.DBW: 2:/Plc/DB18.DBW, Variable
    + DB18.DBD: 2:/Plc/DB18.DBD, Variable
    + DB18.DBX: 2:/Plc/DB18.DBX, Variable
  + DB19: 2:/Plc/DB19, Object
    + DB19.DBB: 2:/Plc/DB19.DBB, Variable
    + DB19.DBW: 2:/Plc/DB19.DBW, Variable
    + DB19.DBD: 2:/Plc/DB19.DBD, Variable
    + DB19.DBX: 2:/Plc/DB19.DBX, Variable
  + DB20: 2:/Plc/DB20, Object
    + DB20.DBB: 2:/Plc/DB20.DBB, Variable
    + DB20.DBW: 2:/Plc/DB20.DBW, Variable
    + DB20.DBD: 2:/Plc/DB20.DBD, Variable
    + DB20.DBX: 2:/Plc/DB20.DBX, Variable
  + DB21: 2:/Plc/DB21, Object
    + DB21.DBB: 2:/Plc/DB21.DBB, Variable
    + DB21.DBW: 2:/Plc/DB21.DBW, Variable
    + DB21.DBD: 2:/Plc/DB21.DBD, Variable
    + DB21.DBX: 2:/Plc/DB21.DBX, Variable
  + DB22: 2:/Plc/DB22, Object
    + DB22.DBB: 2:/Plc/DB22.DBB, Variable
    + DB22.DBW: 2:/Plc/DB22.DBW, Variable
    + DB22.DBD: 2:/Plc/DB22.DBD, Variable
    + DB22.DBX: 2:/Plc/DB22.DBX, Variable
  + DB31: 2:/Plc/DB31, Object
    + DB31.DBB: 2:/Plc/DB31.DBB, Variable
    + DB31.DBW: 2:/Plc/DB31.DBW, Variable
    + DB31.DBD: 2:/Plc/DB31.DBD, Variable
    + DB31.DBX: 2:/Plc/DB31.DBX, Variable
  + DB32: 2:/Plc/DB32, Object
    + DB32.DBB: 2:/Plc/DB32.DBB, Variable
    + DB32.DBW: 2:/Plc/DB32.DBW, Variable
    + DB32.DBD: 2:/Plc/DB32.DBD, Variable
    + DB32.DBX: 2:/Plc/DB32.DBX, Variable
  + DB33: 2:/Plc/DB33, Object
    + DB33.DBB: 2:/Plc/DB33.DBB, Variable
    + DB33.DBW: 2:/Plc/DB33.DBW, Variable
    + DB33.DBD: 2:/Plc/DB33.DBD, Variable
    + DB33.DBX: 2:/Plc/DB33.DBX, Variable
  + DB34: 2:/Plc/DB34, Object
    + DB34.DBB: 2:/Plc/DB34.DBB, Variable
    + DB34.DBW: 2:/Plc/DB34.DBW, Variable
    + DB34.DBD: 2:/Plc/DB34.DBD, Variable
    + DB34.DBX: 2:/Plc/DB34.DBX, Variable
  + DB35: 2:/Plc/DB35, Object
    + DB35.DBB: 2:/Plc/DB35.DBB, Variable
    + DB35.DBW: 2:/Plc/DB35.DBW, Variable
    + DB35.DBD: 2:/Plc/DB35.DBD, Variable
    + DB35.DBX: 2:/Plc/DB35.DBX, Variable
  + DB36: 2:/Plc/DB36, Object
    + DB36.DBB: 2:/Plc/DB36.DBB, Variable
    + DB36.DBW: 2:/Plc/DB36.DBW, Variable
    + DB36.DBD: 2:/Plc/DB36.DBD, Variable
    + DB36.DBX: 2:/Plc/DB36.DBX, Variable
  + DB37: 2:/Plc/DB37, Object
    + DB37.DBB: 2:/Plc/DB37.DBB, Variable
    + DB37.DBW: 2:/Plc/DB37.DBW, Variable
    + DB37.DBD: 2:/Plc/DB37.DBD, Variable
    + DB37.DBX: 2:/Plc/DB37.DBX, Variable
  + DB38: 2:/Plc/DB38, Object
    + DB38.DBB: 2:/Plc/DB38.DBB, Variable
    + DB38.DBW: 2:/Plc/DB38.DBW, Variable
    + DB38.DBD: 2:/Plc/DB38.DBD, Variable
    + DB38.DBX: 2:/Plc/DB38.DBX, Variable
  + DB39: 2:/Plc/DB39, Object
    + DB39.DBB: 2:/Plc/DB39.DBB, Variable
    + DB39.DBW: 2:/Plc/DB39.DBW, Variable
    + DB39.DBD: 2:/Plc/DB39.DBD, Variable
    + DB39.DBX: 2:/Plc/DB39.DBX, Variable
  + DB40: 2:/Plc/DB40, Object
    + DB40.DBB: 2:/Plc/DB40.DBB, Variable
    + DB40.DBW: 2:/Plc/DB40.DBW, Variable
    + DB40.DBD: 2:/Plc/DB40.DBD, Variable
    + DB40.DBX: 2:/Plc/DB40.DBX, Variable
  + DB41: 2:/Plc/DB41, Object
    + DB41.DBB: 2:/Plc/DB41.DBB, Variable
    + DB41.DBW: 2:/Plc/DB41.DBW, Variable
    + DB41.DBD: 2:/Plc/DB41.DBD, Variable
    + DB41.DBX: 2:/Plc/DB41.DBX, Variable
  + DB59: 2:/Plc/DB59, Object
    + DB59.DBB: 2:/Plc/DB59.DBB, Variable
    + DB59.DBW: 2:/Plc/DB59.DBW, Variable
    + DB59.DBD: 2:/Plc/DB59.DBD, Variable
    + DB59.DBX: 2:/Plc/DB59.DBX, Variable
  + DB77: 2:/Plc/DB77, Object
    + DB77.DBB: 2:/Plc/DB77.DBB, Variable
    + DB77.DBW: 2:/Plc/DB77.DBW, Variable
    + DB77.DBD: 2:/Plc/DB77.DBD, Variable
    + DB77.DBX: 2:/Plc/DB77.DBX, Variable
  + DB86: 2:/Plc/DB86, Object
    + DB86.DBB: 2:/Plc/DB86.DBB, Variable
    + DB86.DBW: 2:/Plc/DB86.DBW, Variable
    + DB86.DBD: 2:/Plc/DB86.DBD, Variable
    + DB86.DBX: 2:/Plc/DB86.DBX, Variable
  + DB87: 2:/Plc/DB87, Object
    + DB87.DBB: 2:/Plc/DB87.DBB, Variable
    + DB87.DBW: 2:/Plc/DB87.DBW, Variable
    + DB87.DBD: 2:/Plc/DB87.DBD, Variable
    + DB87.DBX: 2:/Plc/DB87.DBX, Variable
  + DB88: 2:/Plc/DB88, Object
    + DB88.DBB: 2:/Plc/DB88.DBB, Variable
    + DB88.DBW: 2:/Plc/DB88.DBW, Variable
    + DB88.DBD: 2:/Plc/DB88.DBD, Variable
    + DB88.DBX: 2:/Plc/DB88.DBX, Variable
  + DB96: 2:/Plc/DB96, Object
    + DB96.DBB: 2:/Plc/DB96.DBB, Variable
    + DB96.DBW: 2:/Plc/DB96.DBW, Variable
    + DB96.DBD: 2:/Plc/DB96.DBD, Variable
    + DB96.DBX: 2:/Plc/DB96.DBX, Variable
Press any key to continue...
Step 5 - Create a subscription.
Step 6 - Add items to the subscription.
Step 7 - Subscribe to PublishResponse stream.
Press any key to delete the subscription...
Step 8 - Delete the subscription.
Press any key to close the session...

**Comment by rebj1011** [comment] 2018-08-08 07:38
Sadly Visual Studio doesn't create a devenv.log file.

**Comment by rebj1011** [comment] 2018-08-08 07:42
Sadly Visual Studio doesn't create a devenv.log file. There is no error and the ConsoleApp runs till the end.

**Comment by awcullen** [comment] 2018-08-08 21:16
I think the issue is that OpcUa servers can set a limit on the number of nodes that are returned in a BrowseResponse.  I believe the embedded S7 server might do that.  My guess that the number is fifty :)

The way you ask for the next set of nodes is to call BrowseNext with a ContinuationPoint from the previous response.  Below I coded an example of doing that to three levels. 

```
Console.WriteLine("Step 4 - Browse the server namespace.");
Console.WriteLine("+ Root");
var rds1 = new List<ReferenceDescription>();
var browseRequest = new BrowseRequest { NodesToBrowse = new[] { new BrowseDescription { NodeId = NodeId.Parse(ObjectIds.RootFolder), ReferenceTypeId = NodeId.Parse(ReferenceTypeIds.HierarchicalReferences), ResultMask = (uint)BrowseResultMask.TargetInfo, NodeClassMask = (uint)NodeClass.Variable | (uint)NodeClass.Object | (uint)NodeClass.Method, BrowseDirection = BrowseDirection.Forward, IncludeSubtypes = true } } };
var browseResponse = await channel.BrowseAsync(browseRequest);
rds1.AddRange(browseResponse.Results.Where(result => result.References != null).SelectMany(result => result.References));
var cps = browseResponse.Results.Select(br => br.ContinuationPoint).Where(cp => cp != null).ToArray();
while (cps.Length > 0)
{
    var browseNextRequest = new BrowseNextRequest { ContinuationPoints = cps, ReleaseContinuationPoints = false };
    var browseNextResponse = await channel.BrowseNextAsync(browseNextRequest);
    rds1.AddRange(browseNextResponse.Results.Where(result => result.References != null).SelectMany(result => result.References));
}
foreach (var rd1 in rds1)
{
    Console.WriteLine("  + {0}: {1}, {2}", rd1.DisplayName, rd1.BrowseName, rd1.NodeClass);
    var rds2 = new List<ReferenceDescription>();
    browseRequest = new BrowseRequest { NodesToBrowse = new[] { new BrowseDescription { NodeId = ExpandedNodeId.ToNodeId(rd1.NodeId, channel.NamespaceUris), ReferenceTypeId = NodeId.Parse(ReferenceTypeIds.HierarchicalReferences), ResultMask = (uint)BrowseResultMask.TargetInfo, NodeClassMask = (uint)NodeClass.Variable | (uint)NodeClass.Object | (uint)NodeClass.Method, BrowseDirection = BrowseDirection.Forward, IncludeSubtypes = true } } };
    browseResponse = await channel.BrowseAsync(browseRequest);
    rds2.AddRange(browseResponse.Results.Where(result => result.References != null).SelectMany(result => result.References));
    cps = browseResponse.Results.Select(br => br.ContinuationPoint).Where(cp => cp != null).ToArray();
    while (cps.Length > 0)
    {
        var browseNextRequest = new BrowseNextRequest { ContinuationPoints = cps, ReleaseContinuationPoints = false };
        var browseNextResponse = await channel.BrowseNextAsync(browseNextRequest);
        rds2.AddRange(browseNextResponse.Results.Where(result => result.References != null).SelectMany(result => result.References));
    }
    foreach (var rd2 in rds2)
    {
        Console.WriteLine("    + {0}: {1}, {2}", rd2.DisplayName, rd2.BrowseName, rd2.NodeClass);
        var rds3 = new List<ReferenceDescription>();
        browseRequest = new BrowseRequest { NodesToBrowse = new[] { new BrowseDescription { NodeId = ExpandedNodeId.ToNodeId(rd2.NodeId, channel.NamespaceUris), ReferenceTypeId = NodeId.Parse(ReferenceTypeIds.HierarchicalReferences), ResultMask = (uint)BrowseResultMask.TargetInfo, NodeClassMask = (uint)NodeClass.Variable | (uint)NodeClass.Object | (uint)NodeClass.Method, BrowseDirection = BrowseDirection.Forward, IncludeSubtypes = true } } };
        browseResponse = await channel.BrowseAsync(browseRequest);
        rds3.AddRange(browseResponse.Results.Where(result => result.References != null).SelectMany(result => result.References));
        cps = browseResponse.Results.Select(br => br.ContinuationPoint).Where(cp => cp != null).ToArray();
        while (cps.Length > 0)
        {
            var browseNextRequest = new BrowseNextRequest { ContinuationPoints = cps, ReleaseContinuationPoints = false };
            var browseNextResponse = await channel.BrowseNextAsync(browseNextRequest);
            rds3.AddRange(browseNextResponse.Results.Where(result => result.References != null).SelectMany(result => result.References));
        }
        foreach (var rd3 in rds3)
        {
            Console.WriteLine("      + {0}: {1}, {2}", rd3.DisplayName, rd3.BrowseName, rd3.NodeClass);
        }
    }
}
```

**Comment by rebj1011** [comment] 2018-08-09 07:41
Thanks mate now everything works as expected. But three are not enough ;).
You can close this topic.

**Closed** 2018-08-09 12:14 UTC
